### ISSUE TITLE
Miner(s) changing GPU settings automatically 

### ISSUE THREAD

**Issue by pedrojs-sapo** [nicehash/NiceHashMiner#1480]
Hi

Ate least daily I have to reconfigure some GPU's because NMHL or the miners (can't really understand) change GPU settings.
Not all GPU's are changed but it is not always the same GPU and even not only one of them.
I have rigs with 1070 and 1080 and it happens with both.
This also used to happen with NHM but the last released version solved the problem.
Any idea?

Thanks

PJS

**Comment by S74nk0** [comment]
@pedrojs-sapo What do you have to reconfigure? Can you give an example?

**Comment by pedrojs-sapo** [comment]
> 
> 
> @pedrojs-sapo What do you have to reconfigure? Can you give an example?

Hi,

I use MSI AfterBurner and I must set again:"Power Limit, Temp Limit, Core Clock and Memory Clock". It seems that the GPU settings are changed to the "defaults".
I have made tests replacing MSI Afterburner by ASUS GPU Tweak and EVGA Precision X and I keep having GPU settings changed now an then. 
I really can't know if it is NHML or a third party miner that changes the settings but I assume that it can be NHML just because NHM (the discontinued version) also had the same problem (without 3rd party miners) and I think the problem was solved on the last NHM released version.

If you need some more info don't hesitate...

Thanks

Regards

PJS

**Comment by pedrojs-sapo** [comment]
###### UPDATE ######

Hi

I have an Update on this "problem".
The problem is "really" with NiceHash. Now I'm sure.

Since my Power Supply can't handle all GPU's at 100% TDP, I use MSI Afterburner to
keep GPU Power on 80%. Since NiceHash changes GPU settings daily and automatically to 100% TDP, I was getting RIG shutdowns daily.

I like NiceHash a lot but I had to do something because I was loosing money.

Three days ago I started using CUDO Miner. Same "philosophy" as Niceash and also uses 3rd Party Miners.
Its is now 3 days since I'm using CUDO and GPU settings didn't change at all and the Rig is up and running :-).

Could you please try to solve this problem?
I'd like to use NiceHash but I can't till this "bug" is solved.

Thanks

Pedro JS

**Comment by S74nk0** [comment]
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Comment by BigShadex** [comment]
@S74nk0 Can confirm 1.9.1.5 HAS NOT fixed this issue. I have been using 1.9.0.23 for over a month and its been fine.. soon as i updated to 1.9.1.5 ive had it reset my GPUS to 100% default 4 times in 24 hours. 

Not impressed

**Comment by S74nk0** [comment]
@BigShadex on the first run this feature is enabled by **default** on 1.9.1.5 and [1.9.1.6](https://github.com/nicehash/NiceHashMiner/releases/tag/1.9.1.6). You have to disable it in the settings. So first run this is enabled by default. Unless we decide to change this to false by default and we might considering that we have angered a lot of users with this feature

**Comment by Grandoings** [comment]
Still not fixed very upsetting every other half day my rig shuts down.
