### ISSUE TITLE
 NHMWS not connected

### ISSUE THREAD

**Issue by trinitiwowka** [nicehash/NiceHashMiner#2183]
Error  NHMWS not connected. in 3.0.5

**Comment by S74nk0** [comment]
@trinitiwowka Please post logs. Does it connected back eventually?

**Comment by asfyra** [comment]
I have the same problem since this morning, my logs indicate the following error:

```
[2020-10-15 17:05:23] [INFO] [DeviceDetection] DetectCPU START
[2020-10-15 17:05:23] [INFO] [CPUDetector] TryQueryCUDADevicesAsync START cpu -n
[2020-10-15 17:05:23] [ERROR] [DeviceDetectionPrinter] threw Exception: 'Unexpected character encountered while parsing value: A. Path '', line 0, position 0.'. ReadData 'Autoconf failed: Couldn't find L3 cache page.
{"AMD":false,"Intel":true,"IsZen":false,"L3KB_size":0,"Name":"Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz","PhysicalProcessorCount":1,"SupportsAES_SSE42":false,"SupportsAVX":false,"SupportsAVX2":false,"SupportsSSE2":true,"Vendor":"GenuineIntel"}'
[2020-10-15 17:05:23] [INFO] [CPUDetector] TryQueryCUDADevicesAsync END cpu -n
[2020-10-15 17:05:23] [INFO] [CPUDetector] Autoconf failed: Couldn't find L3 cache page.
{"AMD":false,"Intel":true,"IsZen":false,"L3KB_size":0,"Name":"Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz","PhysicalProcessorCount":1,"SupportsAES_SSE42":false,"SupportsAVX":false,"SupportsAVX2":false,"SupportsSSE2":true,"Vendor":"GenuineIntel"}
[2020-10-15 17:05:23] [ERROR] [ApplicationStateManager.Init] Exception: Object reference not set to an instance of an object.
[2020-10-15 17:05:28] [INFO] [UpdateHelpers] NhmAutoUpdateCheckLoop TaskCanceledException: A task was canceled.
[2020-10-15 17:05:28] [INFO] [UpdateHelpers] Exiting NhmAutoUpdateCheckLoop run cleanup

```

I reverted to version 3.0..4.4 and everything works fine

**Comment by mnm279** [comment]
nicehash miner 3.0.5.0 will not launch for me. no error logs as miner is stale and no action can happen. will have to revert on the dead miners. seems to be 4gb card miners on old motherboards affected. rx5700xt miners all fine and launched ok

**Comment by netserver** [comment]
same isue for me, 3.0.4.4 work ok but 3.0.5.0 no internet and no gpu, only one rx580 8gb with latest driver from amd and latest windows update. 

[2020-10-15 19:05:24] [INFO] [NICEHASH] Starting up NiceHash Miner v3.0.5.0
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: en, name: English
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: ru, name: ??????? (Unofficial)
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: es, name: Español (Unofficial)
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: pt, name: Português (Unofficial)
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: bg, name: ????????? (Unofficial)
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: it, name: Italiano (Unofficial)
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: pl, name: Polski (Unofficial)
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: zh_cn, name: ???? (Unofficial)
[2020-10-15 19:05:24] [INFO] [Translations] Found language: code: ro, name: Româna (Unofficial)
[2020-10-15 19:05:24] [INFO] [SystemSpecs] WMI service seems to be running, ManagementObjectSearcher returned success.
[2020-10-15 19:05:24] [INFO] [NHM] Get OS version START
[2020-10-15 19:05:24] [INFO] [NHM] Get OS version END
[2020-10-15 19:05:31] [INFO] [SystemSpecs] FreePhysicalMemory = 416276, 406 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] FreeSpaceInPagingFiles = 32422516, 31662 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] FreeVirtualMemory = 28742288, 28068 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] LargeSystemCache = 0, 0 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] MaxNumberOfProcesses = 4294967295, 4194303 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] MaxProcessMemorySize = 137438953344, 134217727 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] NumberOfLicensedUsers = 0, 0 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] NumberOfProcesses = 118, 0 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] NumberOfUsers = 2, 0 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] OperatingSystemSKU = 48, 0 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] SizeStoredInPagingFiles = 32768000, 32000 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] SuiteMask = 272, 0 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] TotalSwapSpaceSize = 0, 0 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] TotalVirtualMemorySize = 35642932, 34807 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] TotalVisibleMemorySize = 2874932, 2807 MB
[2020-10-15 19:05:31] [INFO] [SystemSpecs] PageFileSize = 32768000, 32000 MB
[2020-10-15 19:05:31] [INFO] [DeviceDetection] DetectCPU START
[2020-10-15 19:05:31] [INFO] [CPUDetector] TryQueryCUDADevicesAsync START cpu -n
[2020-10-15 19:05:31] [ERROR] [DeviceDetectionPrinter] threw Exception: 'Unexpected character encountered while parsing value: A. Path '', line 0, position 0.'. ReadData 'Autoconf failed: Couldn't find L3 cache page.
{"AMD":false,"Intel":true,"IsZen":false,"L3KB_size":0,"Name":"Intel(R) Core(TM)2 CPU          6300  @ 1.86GHz","PhysicalProcessorCount":1,"SupportsAES_SSE42":false,"SupportsAVX":false,"SupportsAVX2":false,"SupportsSSE2":true,"Vendor":"GenuineIntel"}'
[2020-10-15 19:05:31] [INFO] [CPUDetector] TryQueryCUDADevicesAsync END cpu -n
[2020-10-15 19:05:31] [INFO] [CPUDetector] Autoconf failed: Couldn't find L3 cache page.
{"AMD":false,"Intel":true,"IsZen":false,"L3KB_size":0,"Name":"Intel(R) Core(TM)2 CPU          6300  @ 1.86GHz","PhysicalProcessorCount":1,"SupportsAES_SSE42":false,"SupportsAVX":false,"SupportsAVX2":false,"SupportsSSE2":true,"Vendor":"GenuineIntel"}
[2020-10-15 19:05:31] [ERROR] [ApplicationStateManager.Init] Exception: Referencia a objeto no establecida como instancia de un objeto.

**Comment by helpin81** [comment]
same issue here

 [2020-10-15 20:12:33] [INFO] [NICEHASH] Starting up NiceHash Miner v3.0.5.0
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: en, name: English
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: ru, name: Русский (Unofficial)
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: es, name: Español (Unofficial)
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: pt, name: Português (Unofficial)
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: bg, name: Български (Unofficial)
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: it, name: Italiano (Unofficial)
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: pl, name: Polski (Unofficial)
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: zh_cn, name: 简体中文 (Unofficial)
[2020-10-15 20:12:33] [INFO] [Translations] Found language: code: ro, name: Română (Unofficial)
[2020-10-15 20:12:33] [INFO] [SystemSpecs] WMI service seems to be running, ManagementObjectSearcher returned success.
[2020-10-15 20:12:33] [INFO] [NHM] Get OS version START
[2020-10-15 20:12:33] [INFO] [NHM] Get OS version END
[2020-10-15 20:12:34] [INFO] [SystemSpecs] FreePhysicalMemory = 5382100, 5255 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] FreeSpaceInPagingFiles = 11010048, 10752 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] FreeVirtualMemory = 12839080, 12538 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] LargeSystemCache = 0, 0 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] MaxNumberOfProcesses = 4294967295, 4194303 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] MaxProcessMemorySize = 137438953344, 134217727 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] NumberOfLicensedUsers = 0, 0 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] NumberOfProcesses = 166, 0 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] NumberOfUsers = 2, 0 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] OperatingSystemSKU = 4, 0 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] SizeStoredInPagingFiles = 11010048, 10752 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] SuiteMask = 272, 0 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] TotalSwapSpaceSize = 0, 0 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] TotalVirtualMemorySize = 19397108, 18942 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] TotalVisibleMemorySize = 8387060, 8190 MB
[2020-10-15 20:12:34] [INFO] [SystemSpecs] PageFileSize = 11010048, 10752 MB
[2020-10-15 20:12:34] [INFO] [DeviceDetection] DetectCPU START
[2020-10-15 20:12:34] [INFO] [CPUDetector] TryQueryCUDADevicesAsync START cpu -n
[2020-10-15 20:12:34] [ERROR] [DeviceDetectionPrinter] threw Exception: 'Unexpected character encountered while parsing value: A. Path '', line 0, position 0.'. ReadData 'Autoconf failed: Couldn't find L3 cache page.
{"AMD":false,"Intel":true,"IsZen":false,"L3KB_size":0,"Name":"Intel(R) Core(TM)2 Quad CPU    Q9505  @ 2.83GHz","PhysicalProcessorCount":1,"SupportsAES_SSE42":false,"SupportsAVX":false,"SupportsAVX2":false,"SupportsSSE2":true,"Vendor":"GenuineIntel"}'
[2020-10-15 20:12:34] [INFO] [CPUDetector] TryQueryCUDADevicesAsync END cpu -n
[2020-10-15 20:12:34] [INFO] [CPUDetector] Autoconf failed: Couldn't find L3 cache page.
{"AMD":false,"Intel":true,"IsZen":false,"L3KB_size":0,"Name":"Intel(R) Core(TM)2 Quad CPU    Q9505  @ 2.83GHz","PhysicalProcessorCount":1,"SupportsAES_SSE42":false,"SupportsAVX":false,"SupportsAVX2":false,"SupportsSSE2":true,"Vendor":"GenuineIntel"}
[2020-10-15 20:12:34] [ERROR] [ApplicationStateManager.Init] Exception: Referência de objeto não definida para uma instância de um objeto.

**Comment by jimmyhackers** [comment]
i have the same error. (except my cpu is listed)

it looks as if they have removed compatabilty with older cpus......great!!!

CAN THIS BE FIXED PLEASE? im loosing money.

**Comment by S74nk0** [comment]
https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.5.1

There was a critical **bug** with CPU detection that caused the initialization to fail. This was an issue on certain machines (unfortunately yours as well). 

Please install the new version and report back if this fixes your problems.

**Comment by netserver** [comment]
working again for me!  Intel(R) Core(TM)2 CPU 6300 @   

many thaks S74nk0 !!

**Comment by helpin81** [comment]
Updated and solved here! Thank you!

**Comment by IvanMurzak** [comment]
The same error happens again. The last week Nicehash doesn't work.
Version: 3.0.5.4

**Comment by GoudronViande24** [comment]
Did not fix the problem for me

> https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.5.1
> 
> There was a critical **bug** with CPU detection that caused the initialization to fail. This was an issue on certain machines (unfortunately yours as well).
> 
> Please install the new version and report back if this fixes your problems.

**Comment by babu2001** [comment]
I'm having the same issue. Using 3.0.5.6 and 3.0.6.2. Old rigs using GTX1060 3GB and RX480 4GB but also GTX 1070 8GB. Motherboards Asrock AB350 Pro4 and H110 BTC Pro

**Comment by spoedvarkie** [comment]
Getting the same error again, was on 3.0.5.6 and updated to 3.0.6.3 to see if anything changes but still broken. Where else can we report this as nothing seems to be working in order to fix this.

**Comment by GoudronViande24** [comment]
Switched to nice hash quick miner... Now I'm okay

**Comment by AkshayGunplay** [comment]
![image](https://user-images.githubusercontent.com/86151856/122640219-e74f7b00-d11b-11eb-904e-fe50422a7c60.png)
I'm getting this error since yesterday. Did a clean windows install also.
