### ISSUE TITLE
XMRig - failed to start WinRing0 driver, error 183 since NiceHashMiner version 3.0.6.6

### ISSUE THREAD

**Issue by spajdrEX** [nicehash/NiceHashMiner#2537]
When running NiceHashMiner as admin + XMRig miner then starting from version 3.0.6.6 following issue is being reported.:
[2021-10-25 14:52:59.819]  msr      failed to start WinRing0 driver, error 183
[2021-10-25 14:52:59.834]  msr      FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW

_This result in 5-7% performance loss_

When **ENABLED** under **Advanced** -> **Disable Device Status Monitoring** and restarting NiceHashMiner fixes it (running as admin) but of course no temperatures are shown.

I'm running AMD 5600X under Windows 11 Pro , 22000.282 (21H2)

**Comment by BobbyMcPrescott** [comment]
I wish this was the only issue, as I'm sure it would be much easier to fix. Good to know it isn't some Windows 11 update that broke 10 though, as I'm still stuck with one of the first gen Ryzens that don't work with 11.

I actually tried to reinstall it once just because it did actually start showing temps not only for my CPU, but also my 5700XT which previously showed no readings. Same issues. In addition to the topic of this post, there were errors everywhere. Miners would start with default settings mining to god knows where, massive lag, plugins fail to install and just hang there if you reboot and try to start over, etc. The whole program seems to have been thrown off a decimal point.

Oh, I guess it's worth asking, but I doubt it applies if you have 11 as I believe the issue with first gens and 11 is the same core issue, but does MSR mode work for you without it resetting randomly? I can only do Monero mining if I use that custom code that doesn't work in NH, or using NH and hiding the windows so it doesn't constantly reboot on top of what I'm doing.

**Comment by spajdrEX** [comment]
Issue still not fixed in NiceHashMiner version 3.0.6.8

**Comment by sumwatt** [comment]
I get the same issue in 3.0.68. The previous version worked as long as I ran it in Admin mode. I tried using the workaround (Disabling Device monitoring) and while I no longer see the error message, the hash rate is consistent with the degraded performance.

Win 11 Home
AMD 3600
Radeon 5600XT

**Comment by jh0bc** [comment]
Same issue here with an i5 7600 + Win 10 with NiceHashMiner 3.0.6.8

This "When ENABLED under Advanced -> Disable Device Status Monitoring and restarting NiceHashMiner fixes it (running as admin)" worked to temp solve the problem.

**Comment by VaelVictus** [comment]
Three separate CPUs on three separate computers, running with Administrator, had this problem and the solution listed fixed it. I saw anywhere from a 10% to 50% performance boost across all three computers. Note I'm also running the latest xmrig on each of them, simply by placing the new xmrig files over the installation nicehash is using.

**Comment by spajdrEX** [comment]
Can't check now, but did latest update 3.0.6.9 fixed the issue?

**Comment by jh0bc** [comment]
Unfortunately no

**Comment by tmiland** [comment]
Made it work by:

1. Delete/uninstall Nicehash Miner (remover folders and registry references)
2. Delete WinRing0_1_2_0 reference in registry
3. reboot
4. Install with the installer (As user, not Admin) (Remember exceptions in antivirus for the install folder)
5. Run Nicehash as Admin

 Version 3.0.6.9.

**Comment by Stealrull** [comment]
Still having the issue, tried what tmiland posted and no dice. Uninstalled, couldn't even find any mentions of WinRing in registry, deleted all entries of nicehash, rebooted, reinstalled, rebooted, ran as admin same issue still.

5950x running Version 3.0.6.9

Very weird bug I hope can get fixed soon.

**Comment by satanforaday** [comment]
* CPU          AMD Ryzen 9 5950X 16-Core Processor (1) 64-bit AES
                L2:4.0 MB L3:32.0 MB 8C/16T NUMA:1
 * MEMORY       7.3/63.9 GB (11%)
                DIMM_A1: 16 GB DDR4 @ 3600 MHz CMW32GX4M2D3600C18
                DIMM_A2: 16 GB DDR4 @ 3600 MHz CMW32GX4M2D3600C18
                DIMM_B1: 16 GB DDR4 @ 3600 MHz CMW32GX4M2D3600C18
                DIMM_B2: 16 GB DDR4 @ 3600 MHz CMW32GX4M2D3600C18
 * MOTHERBOARD  ASUSTeK COMPUTER INC. - ROG CROSSHAIR VIII HERO (WI-FI)
 * DONATE       1%
 * ASSEMBLY     auto:ryzen
 * POOL #1      172.65.202.202:3380 algo rx/0
 * COMMANDS     hashrate, pause, resume, results, connection
 * HTTP API     127.0.0.1:4000
 * OPENCL       disabled
 * CUDA         disabled
[2021-11-05 13:18:59.153]  net      use pool 172.65.202.202:3380  172.65.202.202
[2021-11-05 13:18:59.153]  net      new job from 172.65.202.202:3380 diff 220503 algo rx/0 height 2486747 (112 tx)
[2021-11-05 13:18:59.153]  cpu      use argon2 implementation AVX2
[2021-11-05 13:18:59.155]  msr      failed to start WinRing0 driver, error 183
[2021-11-05 13:18:59.180]  msr      FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
[2021-11-05 13:18:59.180]  randomx  init dataset algo rx/0 (16 threads) seed 9dde960e83c55c4c...

I am still getting this error after upgrading to the last .9 build. Just wanted to let people know.

**Comment by UltimateByte** [comment]
Exact same issue as @satanforaday with 5950X.
There is no occurrence of "WinRing0" in windows Registry, so I guess it's not worth reinstalling.

**Comment by tmiland** [comment]
The issue came back. 

Temporary solution is to run XMRig with Awesome Miner (enable run mining process with Admin privs)

Start the miner and make sure it's working, then start XMRig with NH.

```
[2021-11-14 14:22:56.083]  msr      service WinRing0_1_2_0 already exists
[2021-11-14 14:22:56.083]  msr      service path: "\??\****\AwesomeMiner\LibreHardwareMonitorLib.sys"
[2021-11-14 14:22:56.577]  msr      register values for "ryzen_19h" preset have been set successfully (493 ms)

```

**Comment by UltimateByte** [comment]
@tmiland Thanks for sharing. Any procedure on how to run "Awesome Miner", more specifically, concurring with XMRig?

**Comment by tmiland** [comment]
> 
> 
> @tmiland Thanks for sharing. Any procedure on how to run "Awesome Miner", more specifically, concurring with XMRig?

No problem. 

Set up a new "managed profit miner", add nicehash pool and wallet, choose the CPU profile.

Go to options -> Managed miners -> Edit (miner) -> Environment, tick the checkbox (enable run mining process with Admin privs)

See: [Getting started with CPU mining (Monero)](https://support.awesomeminer.com/support/solutions/articles/35000180488-getting-started-with-cpu-mining-monero-)

**Comment by tmiland** [comment]
If anyone needs to add the registry entry manually, you can use this: 

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\WinRing0_1_2_0]
"Type"=dword:00000001
"Start"=dword:00000003
"ErrorControl"=dword:00000001
"ImagePath"=hex(2):5c,00,3f,00,3f,00,5c,00,50,00,41,00,54,00,48,00,5f,00,54,00,\
  4f,00,5f,00,4d,00,49,00,4e,00,45,00,52,00,5c,00,57,00,69,00,6e,00,52,00,69,\
  00,6e,00,67,00,30,00,78,00,36,00,34,00,2e,00,73,00,79,00,73,00,00,00
"DisplayName"="WinRing0_1_2_0"

```

Save as `WinRing0_1_2_0.reg` 

Open regedit (as admin), go to `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\WinRing0_1_2_0` and change `ImagePath` to the correct path.

E.g: `C:\Users\User\AppData\Local\Programs\NiceHash Miner\miner_plugins\0e0a7320-94ec-11ea-a64d-17be303ea466\bins\16.0\xmrig-6.8.1\WinRing0x64.sys`

Adding the entry fixed the issue at one time for me, so it might work for others as well.

**Comment by bstrakt** [comment]
This is not a fix, but is what I found: it seems that it conflicts with LibreHardwareMonitorLib.dll from app_3.0.6.9 folder of NiceHash. If monitoring is enabled, it loads that library and the service WinRing0 cannot be created.

**Comment by UltimateByte** [comment]
Now using Arch Linux as a daily driver. No more problem with this kind of Windowsy nonsense, hashrate is now a bit better. 
If you're an advanced PC user and are tired of Microsoft, might be worth learning Linux (not necessarily Arch, which is targetting advanced Linux users).
OFC, I know this won't suit everyone, but I just wanted to remember that Windows isn't an absolute necessity.

**Comment by roboyeti** [comment]
> This is not a fix, but is what I found: it seems that it conflicts with LibreHardwareMonitorLib.dll from app_3.0.6.9 folder of NiceHash. If monitoring is enabled, it loads that library and the service WinRing0 cannot be created.

Aha!  You solved my issue.  If I run LibreHardwareMonitor (the app) after xmrig runs, it works fine.

**Comment by muratia** [comment]
I have fixed the issue by downloading latest XMRig from the github and i replaced the old xmrig and it worked flawlessly

**Comment by MrOrister** [comment]
> I have fixed the issue by downloading latest XMRig from the github and i replaced the old xmrig and it worked flawlessly

This worked for me also! and even service monitoring can be enabled.

**Comment by Dohtar1337** [comment]
XMRig will be updated in the future

**Comment by scorsy63** [comment]
> I have fixed the issue by downloading latest XMRig from the github and i replaced the old xmrig and it worked flawlessly

This fixed it for me.  I was running both NiceHashMiner and xmrig as admin and was still receiving the error message.

**Comment by Vyeche** [comment]
> > I have fixed the issue by downloading latest XMRig from the github and i replaced the old xmrig and it worked flawlessly
> 
> This worked for me also! and even service monitoring can be enabled.

Woo Wee worked for me, too. 
- https://github.com/nicehash/NiceHashMiner/releases

![image](https://github.com/nicehash/NiceHashMiner/assets/972377/e02b9e85-9842-4f6e-921f-68f748779f82)
![image](https://github.com/nicehash/NiceHashMiner/assets/972377/54ad352d-be52-4c95-842b-db2ed2c82780)
