### ISSUE TITLE
unnecessary switch/restart of miner on the same device still on going

### ISSUE THREAD

**Issue by lmlim** [nicehash/NiceHashMiner#266]
Hi,

I found that sometimes NHML is still making unnecessary algo switch/restart, after which the same device is still running the same algo/miner.

I have 5 gpu in a rig, 4 are nvidia 1060, 1 is amd rx480.

the amd is almost always running claymore on dagger-decred. the 4 nvidia are jumping around dag-sia/dag-pasc/dag-decr/dag-lbry/equihash/neoscrypt depending on market price.
but, I notice many times that when nvidias jump to other algos, the amd also restart but it is actually still doing the very same dag-decr. 

restarting the same algos will definitely drag down some of the profit. in addition, devfee also starts at ~15min past the starting point.

thanks.

**Comment by Spoob** [comment]
I have already started such a topic. nothing is decided. I have the same situation. When nvidia goes to another algorithm, it pulls AMD cards behind it.
composition: 3х RX570 + 2х GTX1080ti

**Comment by lmlim** [comment]
yes, too bad. i thought it has been fixed with the lastest ver 1.8.1.2. 
but it has not.

**Comment by jimmyhackers** [comment]
you could always find another machine (cheap pc) to put the rx480 in?

**Comment by noornaim** [comment]
i also got the same issue with legancy 1.8.1.2..
i try to solve this with DDU my GPU driver also no use..
up until i format back my rig and do it all over again (waste my time and money alot) but still not solve the problem.. i use version 2.0 but the profit for nvidia card was reduce alot in dual mining with excavator. should put/use claymore for dual mining for nvdia card.

**Comment by DillonN** [comment]
This should be fixed in the next update
