### ISSUE TITLE
1.8.1.3 freezes

### ISSUE THREAD

**Issue by jorgen180** [nicehash/NiceHashMiner#334]
After upgrade to 1.8.1.3 , GUI freezes when mining starts, leaving impression that cmd window is run on the same thread as GUI. "Nice" work, amateurs.

**Comment by Nicheuji** [comment]
A perfect example of a person standing on a pedestal shouting "I'm an idiot!"
p.s. 1.8.1.3 is working flawlessly for me. Don't jelly.

**Comment by 619Srt** [comment]
Not sure why some people have to be soo salty on here. But I have the same issue as Jorgen180. It crashes when starting to mine and will not respond.

**Comment by sojib0172** [comment]
Same here

**Comment by ChriscomIT** [comment]
@619Srt @sojib0172 How did u installed 1.8.1.3? Did you download the new bin files for the miners? Can you post logs, please? Thanks in advance!

**Comment by sojib0172** [comment]
I was  using 1.8.1.2  
and getting mhs on duel mining about minimum 27mhs maximum 29mhs per GPU.
when I updated my nicehash miner this happens  
yes I had installed legacy 1.8.1.3
On Eth+DCR minig , the problem is -
gpu 0. 0.10mhs . gpu 1. 15.2mhs . gpu 2. 22.0mhs gpu 3. 19mhs  👎 
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1319699/log.txt)

**Comment by sojib0172** [comment]
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1319720/log.txt)
![issue 1 8 1 3](https://user-images.githubusercontent.com/32070018/30675403-16461500-9ea2-11e7-9e41-0aae209b1206.jpg)

I was using 1.8.1.2.
and getting mhs on duel mining about minimum 27mhs maximum 29mhs per GPU.
when I updated my nicehash miner this happens
yes I had installed legacy 1.8.1.3
On Eth+DCR minig , the problem is -
gpu 0. 0.10mhs . gpu 1. 15.2mhs . gpu 2. 22.0mhs gpu 3. 19mhs

**Comment by DillonN** [comment]
Are you all getting the same issue - NHML window stays open but doesn't respond to button clicks or update speed? If you are using CPU mining could you try with that turned off? Also logs are necessary

@sojib0172 are you reporting the freezing issue, or another issue about hashrates on CD?

**Comment by alexvirt77** [comment]
After upgrade to 1.8.1.3 , GUI freezes. Gui window do not respond. A am mining on CPU only. I think, this problem in new xmrstackcpu miner.

**Comment by bladessss** [comment]
I have the same problem from 1.8.1.3 version

**Comment by jimdi** [comment]
I have the same problem from 1.8.1.3 version
GUI not responding after start mining, and when PC goes out from Idle mode miners still works

**Comment by alexvirt77** [comment]
> After upgrade to 1.8.1.3 , GUI freezes. Gui window do not respond. A am mining on CPU only. I think, this problem in new xmrstackcpu miner.

After performing a clean installation in another folder, the problem is solved!

**Comment by DillonN** [comment]
Again can everyone with these issues confirm that they are trying it with the CPU unchecked?

@alexvirt77 that would make sense, since your old folder probably had the old xmr-stak-cpu version which is not compatible with 1.8.1.3. Glad you got it fixed though!

**Comment by jimdi** [comment]
@DillonN yep, with unchecked CPU all works fine

**Comment by DillonN** [comment]
@jimdi you should try deleting the bin folder and letting NHML redownload it (once you launch it with that folder deleted, it will prompt that it is missing files and needs to redownload). Using the CPU miner exe from 1.8.1.2 will cause this behaviour (if e.g. you copied the new files into the old folder, you'd still have the old miner exe's)

**Comment by jimdi** [comment]
thx, it works for me

**Comment by dinicthis** [comment]
New folder solved the problem. New problem, though, with EWBF from 1.8.1.2 and this new version: hashrate drops to zero, and it can't restart, stays at zero, exits with "Code 46." Too bad. EWBF was the highest-rate miner.
